### ISSUE TITLE
csv export

### ISSUE THREAD

**Issue by webervin** [sasha-alias/sqltabs#22]
- as an alternative to share (that posts data to "third party" without asking :-1:
- to local file
- ability to set quoting, line feeds and separator would be nice but not  a must.

**Comment by sasha-alias** [comment]
Agree with the first point, there were a lot of complains about silent sharing. So there will be a dialog in next release.
Not sure about csv. I just can't recall the last time I used export to csv for whatever reason. From my point of view it's a nice to have feature.

**Comment by webervin** [comment]
For CSV: mostly all the same reasons as having button share + but with ability to defer choice on chart type to later time and other person. Also there are accountants and managers who have "deep relationship with spreadsheets" and like to "own" data.

**Comment by sasha-alias** [comment]
SQL Tabs v0.11.0 is out and it has
- dialog before sharing on the web, with ability to enter an own sharing server 
- csv annotation, so in order to get CSV just write:
``` sql
--- csv
select * from pg_class
```

If you are interested in having own sharing server take a look at [sqlshare project](https://github.com/sasha-alias/sqlshare)
It is newborn and not documented yet though.

Closing.
