### ISSUE TITLE
Sorting data on column click

### ISSUE THREAD

**Issue by utopic-men** [sasha-alias/sqltabs#26]
No more "ORDER BY 1/2/3/etc" to write and SQL to re-execute, just click on the column to sort the data.

**Comment by sasha-alias** [comment]
I don't think it will be ever implemented because of the following reasons:
- By the concept, the result output is the reflection of the script you run. So if you manipulate with output directly you will see the different results that supposed to be from the script you see in the editor area. I don't think this is good.
- I've never seen a good sort-by-click mechanism for ordering by multiple columns

**Comment by utopic-men** [comment]
I was sharing your opinion... until I use SquirrelSQL/SQLWorkBench/Postico instead of pgAdmin (on OS X which is not ergonomic...).
It is lacking now I'm accustomed...

A one column sorting mechanism is better than nothing.

PS : I love your block system : simple and SO efficient :+1: :+1: :+1:

**Comment by sasha-alias** [comment]
`v0.18.0` released
