### ISSUE TITLE
Confirm before closing tab

### ISSUE THREAD

**Issue by utopic-men** [sasha-alias/sqltabs#27]
The new tab button is not so far ! :)

**Comment by egor-bayandin** [comment]
Pls. do it configurable :)

**Comment by sasha-alias** [comment]
Personally I don't like dialogs. Though I several times pressed Command+W instead of Command+E and it feels annoying. So I prefer to have an ability to restore the closed tab with its content instead of having confirmation dialogs.
There is a [corresponding item](https://github.com/sasha-alias/sqltabs/issues/9) for this

**Comment by utopic-men** [comment]
Solution : make it configurable (default behaviour : no dialog) as @egor-bayandin  suggested.

**Comment by sasha-alias** [comment]
I'm trying to avoid a configurable behaviour :) The reasons are:
- configurable behaviour is hard to support and it complicates the product
- configurable behaviour means a bad design of UX and it's a poor fix of it

So I agree, there is an issue with closing tabs, but I think restoring should fix it. This is exactly how web-browsers do it, so should be OK I hope.
Although can't promise it to be implemented soon, since I'm busy with another things atm.

**Comment by utopic-men** [comment]
It's OK !

Thank you for your great and promising app !
