### ISSUE TITLE
error: unrecognized configuration parameter "application_name"

### ISSUE THREAD

**Issue by ipolaco** [sasha-alias/sqltabs#80]
I got that error when trying to connect to Amazon Redshift

**Comment by sasha-alias** [comment]
yeah, I have never tested it with redshift.
I think I know what the problem is, but better to spin up a redshift instance to test it.
Expect a fix in a few days, I will report once it's done.
Thank you!

**Comment by sasha-alias** [comment]
Added a very basic support for Amazon Redshift.
Despite Redshift is based on Postgres and shares the same communication protocol it differs a lot from versions of Postgres supported by community.
Expect some functionality not working.

I don't have a permanent access to Redshift. So in order to improve the things I'd need a sponsorship. Please let me know if you are aware of anyone able to provide one.
Also contribution is always welcome!

**Comment by sasha-alias** [comment]
forgot to mention, in order to connect to Redhsifle you need to prepend connection string with a `redshift://` prefix, for example:
```
redshift://user@yourinstance.redshift.amazonaws.com:5439/dev
```

**Comment by ipolaco** [comment]
Have you update the Mac version? Thanks

**Comment by sasha-alias** [comment]
Sorry, not yet. It will take some time to release `v0.15`.
The change is too big for a minor bugfix release.

**Comment by sasha-alias** [comment]
v0.15 released
